CREATE TABLE IF NOT EXISTS tasks (
    id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    title VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    )ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;